### ISSUE TITLE
Either implementations should implement a common interface

### ISSUE THREAD

**Issue by LPeter1997** [WhiteBlackGoose/HonkSharp#13]
It is sometimes useful to be able to handle `Either` variants under a common `IEither` interface, similarly to tuples with `ITuple`. Two use cases come into my mind:
 * Reflection
 * Serialization

The interface could provide the usual `Is<T>()` and `As<T>()` operations, along with a type-erasing accessor, that could return an `object`.

**Comment by WhiteBlackGoose** [comment]
Done, thanks
