### ISSUE TITLE
Pipe for sequences

### ISSUE THREAD

**Issue by WhiteBlackGoose** [WhiteBlackGoose/HonkSharp#16]
Non-lazy, unlike Select

**Comment by Happypig375** [comment]
This is just `ForEach` like in Lists.

**Comment by WhiteBlackGoose** [comment]
But here it's general.

**Comment by Happypig375** [comment]
So why `Pipe` specifically?

**Comment by WhiteBlackGoose** [comment]
Because it pipes all elements through a transformation kinda. Any better suggestion?

**Comment by Happypig375** [comment]
Call it `ForEach`.

**Comment by WhiteBlackGoose** [comment]
But it both maps and executes...

**Comment by Happypig375** [comment]
Then good luck with overload resolution between deciding to pipe each element or the entire sequence as one object.
